#!/bin/bash
getUser=$(cat /etc/passwd | grep $1 | cut -d":" -f1)
if [[ -z $getUser ]]; then
echo "User not exist"
else
	if ! [ -d $2 ];then
		echo "the directory does not exist"
	else
		if [ $UID -eq 0 ]; then
		chown -R  $1:$1 $2
		else echo "You not root"
		fi
	fi 
fi
